# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itineraires_decales_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItinerairesDecalesDialogBase(object):
    def setupUi(self, ItinerairesDecalesDialogBase):
        ItinerairesDecalesDialogBase.setObjectName("ItinerairesDecalesDialogBase")
        ItinerairesDecalesDialogBase.resize(511, 648)
        self.entete = QtWidgets.QWidget(ItinerairesDecalesDialogBase)
        self.entete.setGeometry(QtCore.QRect(10, 10, 491, 631))
        self.entete.setStyleSheet("border-radius: 8px;\n"
"background-color: #FAFBFF;\n"
"\n"
"")
        self.entete.setObjectName("entete")
        self.titre = QtWidgets.QLabel(self.entete)
        self.titre.setGeometry(QtCore.QRect(20, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.titre.setFont(font)
        self.titre.setAutoFillBackground(False)
        self.titre.setStyleSheet("color: #003189; font-size: 20px; font-weight: bold;")
        self.titre.setAlignment(QtCore.Qt.AlignCenter)
        self.titre.setObjectName("titre")
        self.soustitre = QtWidgets.QLabel(self.entete)
        self.soustitre.setGeometry(QtCore.QRect(20, 40, 451, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.soustitre.setFont(font)
        self.soustitre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.soustitre.setStyleSheet("color: #6AAF3D; font-size: 12px; font-style: italic;")
        self.soustitre.setAlignment(QtCore.Qt.AlignCenter)
        self.soustitre.setObjectName("soustitre")
        self.tabWidget = QtWidgets.QTabWidget(self.entete)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 461, 551))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"                \n"
"                border-radius: 0px 6px 6px 6px;\n"
"                background-color: #FFFFFF;\n"
"            }\n"
"\n"
" QTabBar::tab {\n"
"                background-color: #E8EAF0; color: #2C3E50;\n"
"                padding: 10px 0px; min-width: 110px; margin-right: 3px;\n"
"                border-top-left-radius: 6px; border-top-right-radius: 6px;\n"
"                font-weight: bold; font-size: 12px;\n"
"            }\n"
"           \n"
"            QTabBar::tab:selected        { background-color: #003189; color: #FFFFFF; }\n"
"            QTabBar::tab:hover:!selected { background-color: #6AAF3D; color: #FFFFFF; }")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_donnees = QtWidgets.QWidget()
        self.tab_donnees.setObjectName("tab_donnees")
        self.grp_selection_couche = QtWidgets.QGroupBox(self.tab_donnees)
        self.grp_selection_couche.setGeometry(QtCore.QRect(0, 10, 451, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_selection_couche.setFont(font)
        self.grp_selection_couche.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_selection_couche.setObjectName("grp_selection_couche")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.grp_selection_couche)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 431, 131))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.gl_selection_couche = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.gl_selection_couche.setContentsMargins(4, 0, 4, 0)
        self.gl_selection_couche.setSpacing(2)
        self.gl_selection_couche.setObjectName("gl_selection_couche")
        self.label_couche_itineraire = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_couche_itineraire.setFont(font)
        self.label_couche_itineraire.setStyleSheet("color:#003189; min-width:40px;")
        self.label_couche_itineraire.setObjectName("label_couche_itineraire")
        self.gl_selection_couche.addWidget(self.label_couche_itineraire)
        self.btn_browse_iti = QgsFileWidget(self.verticalLayoutWidget_6)
        self.btn_browse_iti.setStyleSheet("\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-family: Consolas, monospace; font-size: 12px; padding: 6px;\n"
"        ")
        self.btn_browse_iti.setObjectName("btn_browse_iti")
        self.gl_selection_couche.addWidget(self.btn_browse_iti)
        self.label_couche_reseau = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_couche_reseau.setStyleSheet("color:#003189; min-width:40px;")
        self.label_couche_reseau.setObjectName("label_couche_reseau")
        self.gl_selection_couche.addWidget(self.label_couche_reseau)
        self.btn_browse_res = QgsFileWidget(self.verticalLayoutWidget_6)
        self.btn_browse_res.setStyleSheet("\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-family: Consolas, monospace; font-size: 12px; padding: 6px;\n"
"        ")
        self.btn_browse_res.setObjectName("btn_browse_res")
        self.gl_selection_couche.addWidget(self.btn_browse_res)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_donnees)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 200, 451, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_valider_donnees = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_valider_donnees.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_valider_donnees.setStyleSheet("QPushButton {\n"
"            background-color: #003189; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover    { background-color: #6AAF3D; }\n"
"        QPushButton:pressed  { background-color: #002060; }\n"
"        QPushButton:disabled { background-color: #B0B8C8; }")
        self.btn_valider_donnees.setObjectName("btn_valider_donnees")
        self.horizontalLayout_2.addWidget(self.btn_valider_donnees)
        self.btn_reset_donnees = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_reset_donnees.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_reset_donnees.setStyleSheet("QPushButton {\n"
"            background-color: #95A5A6; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover { background-color: #7F8C8D; }")
        self.btn_reset_donnees.setObjectName("btn_reset_donnees")
        self.horizontalLayout_2.addWidget(self.btn_reset_donnees)
        self.grp_resume_donnees = QtWidgets.QGroupBox(self.tab_donnees)
        self.grp_resume_donnees.setGeometry(QtCore.QRect(0, 270, 451, 81))
        self.grp_resume_donnees.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_resume_donnees.setObjectName("grp_resume_donnees")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.grp_resume_donnees)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 421, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.gl_chargement_donnees = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.gl_chargement_donnees.setContentsMargins(4, 0, 4, 0)
        self.gl_chargement_donnees.setSpacing(2)
        self.gl_chargement_donnees.setObjectName("gl_chargement_donnees")
        self.label_chargement_itineraires = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_chargement_itineraires.setObjectName("label_chargement_itineraires")
        self.gl_chargement_donnees.addWidget(self.label_chargement_itineraires)
        self.label_chargement_reseau = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_chargement_reseau.setObjectName("label_chargement_reseau")
        self.gl_chargement_donnees.addWidget(self.label_chargement_reseau)
        self.tabWidget.addTab(self.tab_donnees, "")
        self.tab_traitement = QtWidgets.QWidget()
        self.tab_traitement.setObjectName("tab_traitement")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_traitement)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 451, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_lancer_traitement = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_lancer_traitement.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_lancer_traitement.setStyleSheet("QPushButton {\n"
"            background-color: #003189; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover    { background-color: #6AAF3D; }\n"
"        QPushButton:pressed  { background-color: #002060; }\n"
"        QPushButton:disabled { background-color: #B0B8C8; }")
        self.btn_lancer_traitement.setObjectName("btn_lancer_traitement")
        self.horizontalLayout.addWidget(self.btn_lancer_traitement)
        self.btn_reset_traitement = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_reset_traitement.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_reset_traitement.setStyleSheet("QPushButton {\n"
"            background-color: #95A5A6; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover { background-color: #7F8C8D; }")
        self.btn_reset_traitement.setObjectName("btn_reset_traitement")
        self.horizontalLayout.addWidget(self.btn_reset_traitement)
        self.grp_journal_dexecution_1 = QtWidgets.QGroupBox(self.tab_traitement)
        self.grp_journal_dexecution_1.setGeometry(QtCore.QRect(0, 320, 451, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_journal_dexecution_1.setFont(font)
        self.grp_journal_dexecution_1.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_journal_dexecution_1.setObjectName("grp_journal_dexecution_1")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.grp_journal_dexecution_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 431, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.gl_journal_dexe = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.gl_journal_dexe.setContentsMargins(4, 0, 4, 0)
        self.gl_journal_dexe.setSpacing(2)
        self.gl_journal_dexe.setObjectName("gl_journal_dexe")
        self.zl_journal_dexe = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.zl_journal_dexe.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.zl_journal_dexe.setFont(font)
        self.zl_journal_dexe.setStyleSheet("QTextEdit {\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-size: 12px; padding: 6px;\n"
"        }")
        self.zl_journal_dexe.setReadOnly(True)
        self.zl_journal_dexe.setObjectName("zl_journal_dexe")
        self.gl_journal_dexe.addWidget(self.zl_journal_dexe)
        self.grp_apparence_iti = QtWidgets.QGroupBox(self.tab_traitement)
        self.grp_apparence_iti.setGeometry(QtCore.QRect(0, 10, 451, 151))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_apparence_iti.setFont(font)
        self.grp_apparence_iti.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_apparence_iti.setObjectName("grp_apparence_iti")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.grp_apparence_iti)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(10, 20, 431, 121))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.gl_apparence_iti = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.gl_apparence_iti.setContentsMargins(4, 0, 4, 0)
        self.gl_apparence_iti.setSpacing(2)
        self.gl_apparence_iti.setObjectName("gl_apparence_iti")
        self.label_couleur_iti = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_couleur_iti.setFont(font)
        self.label_couleur_iti.setStyleSheet("color:#003189; min-width:40px;")
        self.label_couleur_iti.setObjectName("label_couleur_iti")
        self.gl_apparence_iti.addWidget(self.label_couleur_iti)
        self.btn_browse_couleur_iti_ = QgsFileWidget(self.verticalLayoutWidget_13)
        self.btn_browse_couleur_iti_.setStyleSheet("\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-family: Consolas, monospace; font-size: 12px; padding: 6px;\n"
"        ")
        self.btn_browse_couleur_iti_.setObjectName("btn_browse_couleur_iti_")
        self.gl_apparence_iti.addWidget(self.btn_browse_couleur_iti_)
        self.label_largeur = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_largeur.setFont(font)
        self.label_largeur.setStyleSheet("color:#003189; min-width:40px;")
        self.label_largeur.setObjectName("label_largeur")
        self.gl_apparence_iti.addWidget(self.label_largeur)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.slider_largeur = QtWidgets.QSlider(self.verticalLayoutWidget_13)
        self.slider_largeur.setMaximum(15)
        self.slider_largeur.setPageStep(1)
        self.slider_largeur.setOrientation(QtCore.Qt.Horizontal)
        self.slider_largeur.setInvertedAppearance(False)
        self.slider_largeur.setObjectName("slider_largeur")
        self.horizontalLayout_7.addWidget(self.slider_largeur)
        self.valeur_largeur = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.valeur_largeur.setObjectName("valeur_largeur")
        self.horizontalLayout_7.addWidget(self.valeur_largeur)
        self.gl_apparence_iti.addLayout(self.horizontalLayout_7)
        self.grp_progression = QtWidgets.QGroupBox(self.tab_traitement)
        self.grp_progression.setGeometry(QtCore.QRect(0, 230, 451, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_progression.setFont(font)
        self.grp_progression.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_progression.setObjectName("grp_progression")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.grp_progression)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 431, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.gl_progression = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.gl_progression.setContentsMargins(4, 0, 4, 0)
        self.gl_progression.setSpacing(2)
        self.gl_progression.setObjectName("gl_progression")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setMinimumSize(QtCore.QSize(11, 0))
        self.progressBar.setStyleSheet("\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8;\n"
"            font-size: 12px; padding: 6px;\n"
"        ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gl_progression.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tab_traitement, "")
        self.tab_selection = QtWidgets.QWidget()
        self.tab_selection.setAutoFillBackground(False)
        self.tab_selection.setObjectName("tab_selection")
        self.grp_selection = QtWidgets.QGroupBox(self.tab_selection)
        self.grp_selection.setGeometry(QtCore.QRect(0, 10, 451, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_selection.setFont(font)
        self.grp_selection.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_selection.setObjectName("grp_selection")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.grp_selection)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 431, 61))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.gl_selection = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.gl_selection.setContentsMargins(4, 0, 4, 0)
        self.gl_selection.setSpacing(2)
        self.gl_selection.setObjectName("gl_selection")
        self.btn_activer_selection = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.btn_activer_selection.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_activer_selection.setStyleSheet("QPushButton {\n"
"            background-color: #FFFFFF; color: #003189;\n"
"            border: 2px solid #003189; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover   { background-color: #003189; color: #FFFFFF; }\n"
"        QPushButton:pressed { background-color: #002060; color: #FFFFFF; }")
        self.btn_activer_selection.setObjectName("btn_activer_selection")
        self.gl_selection.addWidget(self.btn_activer_selection)
        self.grp_ech_pos = QtWidgets.QGroupBox(self.tab_selection)
        self.grp_ech_pos.setGeometry(QtCore.QRect(0, 120, 451, 101))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_ech_pos.setFont(font)
        self.grp_ech_pos.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_ech_pos.setObjectName("grp_ech_pos")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.grp_ech_pos)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 431, 71))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.gl_ech_pos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.gl_ech_pos.setContentsMargins(4, 0, 4, 0)
        self.gl_ech_pos.setSpacing(2)
        self.gl_ech_pos.setObjectName("gl_ech_pos")
        self.btn_activer_echanges = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.btn_activer_echanges.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_activer_echanges.setStyleSheet("QPushButton {\n"
"            background-color: #FFFFFF; color: #003189;\n"
"            border: 2px solid #003189; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover   { background-color: #003189; color: #FFFFFF; }\n"
"        QPushButton:pressed { background-color: #002060; color: #FFFFFF; }")
        self.btn_activer_echanges.setObjectName("btn_activer_echanges")
        self.gl_ech_pos.addWidget(self.btn_activer_echanges)
        self.tabWidget.addTab(self.tab_selection, "")
        self.tab_export = QtWidgets.QWidget()
        self.tab_export.setObjectName("tab_export")
        self.grp_export = QtWidgets.QGroupBox(self.tab_export)
        self.grp_export.setGeometry(QtCore.QRect(0, 10, 451, 171))
        self.grp_export.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_export.setTitle("")
        self.grp_export.setObjectName("grp_export")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.grp_export)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_format_export = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_format_export.setFont(font)
        self.label_format_export.setStyleSheet("color:#003189; min-width:40px;")
        self.label_format_export.setObjectName("label_format_export")
        self.verticalLayout.addWidget(self.label_format_export)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_export_shp = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_export_shp.setObjectName("btn_export_shp")
        self.horizontalLayout_8.addWidget(self.btn_export_shp)
        self.btn_export_gpkg = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_export_gpkg.setObjectName("btn_export_gpkg")
        self.horizontalLayout_8.addWidget(self.btn_export_gpkg)
        self.btn_export_png = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_export_png.setObjectName("btn_export_png")
        self.horizontalLayout_8.addWidget(self.btn_export_png)
        self.btn_export_pdf = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_export_pdf.setObjectName("btn_export_pdf")
        self.horizontalLayout_8.addWidget(self.btn_export_pdf)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_destination = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_destination.setFont(font)
        self.label_destination.setStyleSheet("color:#003189; min-width:40px;")
        self.label_destination.setObjectName("label_destination")
        self.verticalLayout.addWidget(self.label_destination)
        self.btn_browse_destination = QgsFileWidget(self.verticalLayoutWidget)
        self.btn_browse_destination.setStyleSheet("\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-family: Consolas, monospace; font-size: 12px; padding: 6px;\n"
"        ")
        self.btn_browse_destination.setObjectName("btn_browse_destination")
        self.verticalLayout.addWidget(self.btn_browse_destination)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_export)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 200, 451, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_exporter = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_exporter.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_exporter.setStyleSheet("QPushButton {\n"
"            background-color: #6AAF3D; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover { background-color: #5a9e2f; }")
        self.btn_exporter.setObjectName("btn_exporter")
        self.horizontalLayout_9.addWidget(self.btn_exporter)
        self.btn_reset_export = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_reset_export.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_reset_export.setStyleSheet("QPushButton {\n"
"            background-color: #95A5A6; color: #FFFFFF;\n"
"            border: none; border-radius: 6px;\n"
"            padding: 8px 16px; font-weight: bold; font-size: 13px;\n"
"        }\n"
"        QPushButton:hover { background-color: #7F8C8D; }")
        self.btn_reset_export.setObjectName("btn_reset_export")
        self.horizontalLayout_9.addWidget(self.btn_reset_export)
        self.grp_journal_dexport = QtWidgets.QGroupBox(self.tab_export)
        self.grp_journal_dexport.setGeometry(QtCore.QRect(0, 270, 451, 211))
        self.grp_journal_dexport.setStyleSheet("QGroupBox {\n"
"            border: 2px solid #D0D4E8; border-radius: 8px;\n"
"            margin-top: 14px; padding: 12px 10px 10px 10px;\n"
"            background-color: #FAFBFF;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin; subcontrol-position: top left;\n"
"            left: 12px; padding: 0 6px;\n"
"            color: #003189; font-weight: bold; font-size: 13px;\n"
"        }")
        self.grp_journal_dexport.setObjectName("grp_journal_dexport")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.grp_journal_dexport)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 431, 161))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.gl_journal_dexport = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.gl_journal_dexport.setContentsMargins(4, 0, 4, 0)
        self.gl_journal_dexport.setSpacing(2)
        self.gl_journal_dexport.setObjectName("gl_journal_dexport")
        self.zl_journal_dexport = QtWidgets.QTextEdit(self.verticalLayoutWidget_8)
        self.zl_journal_dexport.setMinimumSize(QtCore.QSize(0, 10))
        self.zl_journal_dexport.setStyleSheet("QTextEdit {\n"
"            border: 2px solid #D0D4E8; border-radius: 6px;\n"
"            background-color: #F0F2F8; color: #2C3E50;\n"
"            font-family: Consolas, monospace; font-size: 12px; padding: 6px;\n"
"        }")
        self.zl_journal_dexport.setReadOnly(True)
        self.zl_journal_dexport.setObjectName("zl_journal_dexport")
        self.gl_journal_dexport.addWidget(self.zl_journal_dexport)
        self.tabWidget.addTab(self.tab_export, "")

        self.retranslateUi(ItinerairesDecalesDialogBase)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ItinerairesDecalesDialogBase)

    def retranslateUi(self, ItinerairesDecalesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ItinerairesDecalesDialogBase.setWindowTitle(_translate("ItinerairesDecalesDialogBase", "Itinéraires Décalés"))
        self.titre.setText(_translate("ItinerairesDecalesDialogBase", "Cartographie des itinéraires de randonnée"))
        self.soustitre.setText(_translate("ItinerairesDecalesDialogBase", "Style plan de bus"))
        self.grp_selection_couche.setTitle(_translate("ItinerairesDecalesDialogBase", "Sélection des couches"))
        self.label_couche_itineraire.setText(_translate("ItinerairesDecalesDialogBase", "Couche itinéraires : "))
        self.btn_browse_iti.setDialogTitle(_translate("ItinerairesDecalesDialogBase", "Chemin vers itineraire.shp ..."))
        self.label_couche_reseau.setText(_translate("ItinerairesDecalesDialogBase", "Couche réseau : "))
        self.btn_browse_res.setDialogTitle(_translate("ItinerairesDecalesDialogBase", "Chemin vers itineraire.shp ..."))
        self.btn_valider_donnees.setText(_translate("ItinerairesDecalesDialogBase", "Valider les données"))
        self.btn_reset_donnees.setText(_translate("ItinerairesDecalesDialogBase", "Réinitialiser"))
        self.grp_resume_donnees.setTitle(_translate("ItinerairesDecalesDialogBase", "Chargement des données"))
        self.label_chargement_itineraires.setText(_translate("ItinerairesDecalesDialogBase", "Itinéraires : non chargés"))
        self.label_chargement_reseau.setText(_translate("ItinerairesDecalesDialogBase", "Réseau : non chargé"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_donnees), _translate("ItinerairesDecalesDialogBase", "Données"))
        self.btn_lancer_traitement.setText(_translate("ItinerairesDecalesDialogBase", "Lancer tous les traitements"))
        self.btn_reset_traitement.setText(_translate("ItinerairesDecalesDialogBase", "Réinitialiser"))
        self.grp_journal_dexecution_1.setTitle(_translate("ItinerairesDecalesDialogBase", "Journal d\'éxécution"))
        self.zl_journal_dexe.setHtml(_translate("ItinerairesDecalesDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#f0f2f8;\"><br /></p></body></html>"))
        self.grp_apparence_iti.setTitle(_translate("ItinerairesDecalesDialogBase", "Apparence des itinéraires"))
        self.label_couleur_iti.setText(_translate("ItinerairesDecalesDialogBase", "Téléchargez un fichier gérant la couleur des itinéraires :"))
        self.btn_browse_couleur_iti_.setDialogTitle(_translate("ItinerairesDecalesDialogBase", "Chemin vers itineraire.shp ..."))
        self.label_largeur.setText(_translate("ItinerairesDecalesDialogBase", "Choisir l\'épaisseur des traits : "))
        self.valeur_largeur.setText(_translate("ItinerairesDecalesDialogBase", "0 unité de carte"))
        self.grp_progression.setTitle(_translate("ItinerairesDecalesDialogBase", "Progression"))
        self.progressBar.setFormat(_translate("ItinerairesDecalesDialogBase", "En attente..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_traitement), _translate("ItinerairesDecalesDialogBase", "Traitement"))
        self.grp_selection.setTitle(_translate("ItinerairesDecalesDialogBase", "Sélectionner un stroke"))
        self.btn_activer_selection.setText(_translate("ItinerairesDecalesDialogBase", "Activer la sélection par click"))
        self.grp_ech_pos.setTitle(_translate("ItinerairesDecalesDialogBase", "Echanger la position de deux strokes "))
        self.btn_activer_echanges.setText(_translate("ItinerairesDecalesDialogBase", "Activer la phase d\'échange de strokes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_selection), _translate("ItinerairesDecalesDialogBase", "Sélection"))
        self.label_format_export.setText(_translate("ItinerairesDecalesDialogBase", "Choisir un format d\'export :"))
        self.btn_export_shp.setText(_translate("ItinerairesDecalesDialogBase", "Shapefile"))
        self.btn_export_gpkg.setText(_translate("ItinerairesDecalesDialogBase", "GeoPackage"))
        self.btn_export_png.setText(_translate("ItinerairesDecalesDialogBase", "PNG (carte)"))
        self.btn_export_pdf.setText(_translate("ItinerairesDecalesDialogBase", "PDF (carte)"))
        self.label_destination.setText(_translate("ItinerairesDecalesDialogBase", "Choisir un dossier de destination :"))
        self.btn_exporter.setText(_translate("ItinerairesDecalesDialogBase", "Exporter"))
        self.btn_reset_export.setText(_translate("ItinerairesDecalesDialogBase", "Réinitialiser"))
        self.grp_journal_dexport.setTitle(_translate("ItinerairesDecalesDialogBase", "Journal d\'éxécution"))
        self.zl_journal_dexport.setHtml(_translate("ItinerairesDecalesDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'monospace\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_export), _translate("ItinerairesDecalesDialogBase", "Export"))
from qgsfilewidget import QgsFileWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItinerairesDecalesDialogBase = QtWidgets.QDialog()
    ui = Ui_ItinerairesDecalesDialogBase()
    ui.setupUi(ItinerairesDecalesDialogBase)
    ItinerairesDecalesDialogBase.show()
    sys.exit(app.exec_())
