# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ItinerairesDecalesDialog
                                 A QGIS plugin
 Représentation d'itinéraires multiples décalés à la manière des plans de bus
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Titouan Courgey, Nada Ed-Dariy, Sarah Forcieri et Augustin-Pierre Hostein (IGAST25) 
        email                : sarah.forcieri@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import time
from qgis.gui import QgsFileWidget
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog, QApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsProject, QgsVectorLayer
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'itineraires_decales_dialog_base.ui'))


from .core.traitement import lancer_tout
from .core.export import exporter_couches
from .core.selection import SelectItineraire


class ItinerairesDecalesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ItinerairesDecalesDialog, self).__init__(parent)
        self.setWindowTitle("Projet Analyse Spatiale 2026 - Itinéraires Comme Des Bus")

        self.layer_iti          = None
        self.layer_res          = None
        self.layer_strokesroute = None
        self.layer_iti_eclate   = None
        self.layer_fusion_iti   = None
        self.layer_noeuds       = None
        self.index_nodes        = None
        self.layer_strokes_iti  = None
        self.temps_debut        = None

        plugin_dir = os.path.dirname(__file__)
        icon_path = os.path.join(plugin_dir, "icons", "icon_plug.png")
        self.setWindowIcon(QIcon(icon_path))

        self.setupUi(self)
        self._onglet_donnees()
        self._onglet_traitement()
        self._onglet_selection()
        self._onglet_export()
        
    # =============================================================================
    # Onglet Données
    # =============================================================================

    def _onglet_donnees(self):
        self.btn_valider_donnees.clicked.connect(self._valider_donnees)
        self.btn_reset_donnees.clicked.connect(self._reset_donnees)

    def _valider_donnees(self):
        chemin_iti = self.btn_browse_iti.filePath()
        chemin_res = self.btn_browse_res.filePath()

        self.layer_iti = QgsVectorLayer(chemin_iti, "itinéraire", "ogr") if chemin_iti else None
        self.layer_res = QgsVectorLayer(chemin_res, "réseau", "ogr")     if chemin_res else None

        if self.layer_iti and self.layer_iti.isValid():
            QgsProject.instance().addMapLayer(self.layer_iti)
            self.label_chargement_itineraires.setText(f"OK  Itinéraires : {self.layer_iti.featureCount()} entités")
        else:
            self.label_chargement_itineraires.setText("ERR  Itinéraires : fichier invalide")
            self.layer_iti = None

        if self.layer_res and self.layer_res.isValid():
            QgsProject.instance().addMapLayer(self.layer_res)
            self.label_chargement_reseau.setText(f"OK  Réseau : {self.layer_res.featureCount()} entités")
        else:
            self.label_chargement_reseau.setText("ERR  Réseau : fichier invalide")
            self.layer_res = None

    def _reset_donnees(self):
        if self.layer_iti:
            QgsProject.instance().removeMapLayer(self.layer_iti.id())
        if self.layer_res:
            QgsProject.instance().removeMapLayer(self.layer_res.id())

        self.layer_iti = None
        self.layer_res = None

        self.btn_browse_iti.setFilePath("")
        self.btn_browse_res.setFilePath("")

        self.label_chargement_itineraires.setText("Itinéraires : non chargés")
        self.label_chargement_reseau.setText("Réseau : non chargé")
        

    # =============================================================================
    # Onglet Traitement
    # =============================================================================

    def _onglet_traitement(self):
        self.btn_lancer_traitement.clicked.connect(self._lancer_traitement)
        self.btn_reset_traitement.clicked.connect(self._reset_traitement)
        self.progressBar.setValue(0); self.progressBar.setFormat("En attente...")

    def _log(self, msg, onglet="traitement"):
        if onglet == "traitement":
            self.zl_journal_dexe.append(msg)  # <--- CORRIGÉ ICI (sans le _1)
        elif onglet == "export":
            self.zl_journal_dexport.append(msg)

        QApplication.processEvents()

    def _verifier_pret(self):
        if not self.layer_iti or not self.layer_res:
            self._log("ERR  Veuillez d'abord valider les donnees dans l'onglet Donnees !")
            return False
        return True

    def _reset_traitement(self):
        self.layer_strokesroute = None
        self.layer_iti_eclate   = None
        self.layer_fusion_iti   = None
        self.layer_noeuds       = None
        self.index_nodes        = None
        self.layer_strokes_iti  = None
        self.temps_debut        = None
        self.zl_journal_dexe.clear()
        self.progressBar.setValue(0); self.progressBar.setFormat("En attente...")

    def _maj_progression_traitement(self, pourcentage, message):
        """Met à jour la barre de progression."""
        self.progressBar.setValue(pourcentage)
        self.zl_journal_dexe.append(message)
        
        QApplication.processEvents()

    def _lancer_traitement(self):
        """
        Orchestre le lancement de toutes les fonctions liées à la création des strokes
        """
        
        chemin_iti = self.btn_browse_iti.filePath()
        chemin_res = self.btn_browse_res.filePath()

        largeur = 2
        tolerance = 0.01

        if not chemin_iti or not chemin_res:
            self._log("ERR : Veuillez sélectionner les fichiers itinéraire et réseau.")
            return

        self.temps_debut = time.time()
        self._log(">>> Lancement du processus complet...")
        
        try:
            self._maj_progression_traitement(5, "Démarrage du traitement...")

            resultats = lancer_tout(chemin_iti, chemin_res, largeur, tolerance, progression=self._maj_progression_traitement)

            self.layer_iti = resultats.get("layer_iti")
            self.layer_res = resultats.get("layer_res")
            self.layer_strokesroute = resultats.get("layer_strokesroute")
            self.layer_strokes_iti = resultats.get("layer_strokes_iti")
            
            duree = round(time.time() - self.temps_debut, 1)
            self._maj_progression_traitement(100, f"Traitement terminé avec succès en {duree} secondes !")
            self._log(f"Couche générée : {self.layer_strokes_iti.featureCount()} strokes d'itinéraires.")

        except Exception as e:
            self._log(f"ERREUR CRITIQUE durant le traitement : {str(e)}")
            self.progressBar.setValue(0)
            self._maj_progression_traitement(0, "Erreur de traitement")
    

    # =============================================================================
    # Onglet Sélection
    # =============================================================================

    def _onglet_selection(self):
        # On relie les boutons
        self.btn_activer_selection.clicked.connect(self._lancer_selection)
        self.btn_activer_echanges.clicked.connect(self._lancer_echange)
        
        self.outil_carte_actif = None

    def _lancer_selection(self):
        if not self.layer_strokes_iti:
            self._log("ERR : Couche des strokes manquante.")
            return
            
        canvas = iface.mapCanvas()
        self.outil_carte_actif = SelectItineraire(canvas, self.layer_strokes_iti, largeur=2, mode="selection")
        canvas.setMapTool(self.outil_carte_actif)
        self._log("OK : Mode sélection activé sur la carte.")

    def _lancer_echange(self):
        if not self.layer_strokes_iti:
            self._log("ERR : Couche des strokes manquante.")
            return
            
        canvas = iface.mapCanvas()
        # On passe le paramètre mode="echange" à ton outil
        self.outil_carte_actif = SelectItineraire(canvas, self.layer_strokes_iti, largeur=2, mode="echange")
        canvas.setMapTool(self.outil_carte_actif)
        self._log("OK : Mode échange activé sur la carte.")

        

    # =============================================================================
    # Onglet Export
    # =============================================================================

    def _onglet_export(self):
        self.btn_browse_destination.setStorageMode(QgsFileWidget.GetDirectory)
        self.btn_exporter.clicked.connect(self._lancer_export)
        self.btn_reset_export.clicked.connect(self._reset_export)
    
    def _lancer_export(self):
        """
        Prépare les données en lisant les boutons radio et lance l'export.
        """
        # Récupérer le dossier de destination
        dossier = self.btn_browse_destination.filePath()
        
        if not dossier:
            self._log("ERR : Veuillez choisir un dossier de destination.", onglet="export")
            return

        # Vérifier quel bouton radio est coché pour définir le format
        fmt = None
        if self.btn_export_gpkg.isChecked():
            fmt = "GeoPackage"
        elif self.btn_export_shp.isChecked():
            fmt = "ESRI Shapefile"
        elif self.btn_export_png.isChecked():
            fmt = "PNG"
        elif self.btn_export_pdf.isChecked():
            fmt = "PDF"

        if not fmt:
            self._log("ERR : Veuillez cocher un format d'export.", onglet="export")
            return

        couches_a_exporter = [
            ("strokes_routiers", self.layer_strokesroute),
            ("strokes_itineraires", self.layer_strokes_iti)
        ]

        # Récupérer le canvas de QGIS
        canvas = iface.mapCanvas()

        # Lancer l'export 
        self._log(f">>> Lancement de l'export au format {fmt}...", onglet="export")
        
        exporter_couches(couches_a_exporter, dossier, fmt, canvas, self.zl_journal_dexport)

    def _reset_export(self):
        """
        Remet à zéro les champs de l'onglet export.
        """
        # Vider la barre de destination
        self.btn_browse_destination.setFilePath("")
        
        # Décocher tous les boutons radio
        self.btn_export_gpkg.setAutoExclusive(False)
        self.btn_export_shp.setAutoExclusive(False)
        self.btn_export_png.setAutoExclusive(False)
        self.btn_export_pdf.setAutoExclusive(False)
        
        self.btn_export_gpkg.setChecked(False)
        self.btn_export_shp.setChecked(False)
        self.btn_export_png.setChecked(False)
        self.btn_export_pdf.setChecked(False)
        
        self.btn_export_gpkg.setAutoExclusive(True)
        self.btn_export_shp.setAutoExclusive(True)
        self.btn_export_png.setAutoExclusive(True)
        self.btn_export_pdf.setAutoExclusive(True)
        
        self._log("Champs d'export réinitialisés.", onglet="export")

